name: Build flashable kernel (MIUI/HyperOS renoir)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Kernel Source Code
      uses: actions/checkout@v3
      with:
        github-server-url: 'https://github.com'
        repository: aj4664/android_kernel_xiaomi_sm8350-miui
        ref: hyper-14
        path: kernel-srcroot
    
    - name: Setup Build Environment
      run: |
        sudo apt-get update
        sudo apt install -y libelf-dev lld llvm gcc binutils-arm-linux-gnueabi binutils-aarch64-linux-gnu curl wget vim git ccache automake flex lzop bison gperf build-essential zip zlib1g-dev g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 x11proto-core-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler kmod python3 python3-pip

    - name: Setup Nathan Slim Clang
      run: |
        mkdir ./toolchain
        cd ./toolchain
        curl -o llvm-18.tar.gz https://mirrors.edge.kernel.org/pub/tools/llvm/files/llvm-18.1.8-x86_64.tar.gz
        tar -xvf llvm-18.tar.gz
        TARGET_CLANG_PATH="$(pwd)/$(find ./ -name "bin")"
        echo "TARGET_CLANG_PATH=${TARGET_CLANG_PATH}" > $GITHUB_ENV

    - name: Setup Kernel SU
      run: |
        cd kernel-srcroot
        git submodule init
        git submodule update --checkout

    - name: Build Kernel for renoir
      run: |
        cd kernel-srcroot
        PATH=${{ env.TARGET_CLANG_PATH }}/:$PATH
        clang --version

        bash build.sh defconfig liaa
        bash build.sh all lisa

        echo "TARGET_KERNEL_FLASHABLE_NAME=$(ls ../out/anykernel/ | grep Acetaminophen)" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.TARGET_KERNEL_FLASHABLE_NAME }}
        path: out/anykernel/Acetaminophen-kernel-*
